### ISSUE TITLE
Unable to reference a middleware from another namespace ingressroute

### ISSUE THREAD

**Issue by OlivierAlves** [traefik/yaegi#1223]
### The following  triggers an unexpected result

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: traefik
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authelia-route
  namespace: authentication
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`auth.domain.com`)
      services:
        - kind: Service
          name: auth-service
          port: 9090
      middlewares:
        - name: traefik-redirectscheme@kubernetescrd
```

### Expected result

```console
Everything runs fine (prior to  v2.5.0 it was the case)
```

### Got

```console
level=error msg="Failed to create middleware keys: invalid reference to middleware traefik-security@kubernetescrd: with crossnamespace disallowed, the namespace field needs to be explicitly specified" providerName=kubernetescrd ingress=authelia-route-secure namespace=authentication
```

### Yaegi Version

latest

### Additional Notes

Nothing (at all) besides the Traefik version has changed to 2.5.0
